import {
  Bot,
  Mail,
  Globe,
  ShoppingCart,
  BarChart3,
  MessageSquare,
  FileText,
  Search,
  Zap,
  Building2,
  GraduationCap,
  Heart,
  Truck,
  Hotel,
  Briefcase,
  TrendingUp,
  Users,
  Calendar,
  Phone,
  Shield,
  Database,
  Cpu,
  Store,
  Megaphone,
  BookOpen,
  Home,
  DollarSign,
  ClipboardList,
  Stethoscope,
  Scale,
} from 'lucide-react'

export interface Product {
  id: string
  name: string
  category: 'ready' | 'custom' | 'idea'
  icon: any
  niche: string
  benefits: string[]
  price: number
  priceLabel: string
  telegramDemoLink: string
}

export const products: Product[] = [

  // ══════════════════════════════
  // READY TO BUY — 10 products
  // ══════════════════════════════

  {
    id: 'r1',
    name: 'Sports Prediction Telegram Bot',
    category: 'ready',
    icon: BarChart3,
    niche: 'Sports Betting',
    benefits: [
      'Delivers AI-powered match predictions with confidence scores across EPL, La Liga, Bundesliga and more',
      'Sends daily fixture analysis directly to your Telegram channel or group automatically',
      'Built-in form tracking, head-to-head stats and over/under predictions for every match',
    ],
    price: 800,
    priceLabel: '$800',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r2',
    name: 'Cold Email Outreach System',
    category: 'ready',
    icon: Mail,
    niche: 'Sales & Marketing',
    benefits: [
      'Upload a CSV of leads, set your template, and send personalized emails at scale in minutes',
      'Built-in AI personalization that rewrites each email based on the recipient profile',
      'Tracks opens, clicks and replies with a clean dashboard — no third party tools needed',
    ],
    price: 500,
    priceLabel: '$500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r3',
    name: 'Web Scraping & Lead Extraction Tool',
    category: 'ready',
    icon: Search,
    niche: 'Lead Generation',
    benefits: [
      'Scrapes business listings, contact details and emails from Google Maps and directories automatically',
      'Exports clean CSV files ready to import into any CRM or email tool instantly',
      'Supports proxy rotation and scheduling so scraping runs without interruption or blocks',
    ],
    price: 500,
    priceLabel: '$500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r4',
    name: 'Shortlet Booking Website',
    category: 'ready',
    icon: Home,
    niche: 'Real Estate & Hospitality',
    benefits: [
      'Professional booking website built specifically for shortlet apartment owners in Nigeria',
      'WhatsApp booking button pre-filled with availability message routes directly to the owner',
      'Includes property photos, Google Maps location, amenities list and mobile optimized design',
    ],
    price: 300,
    priceLabel: '₦100,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r5',
    name: 'E-commerce Store with AI Product Descriptions',
    category: 'ready',
    icon: ShoppingCart,
    niche: 'E-commerce',
    benefits: [
      'Fully functional online store with product pages, cart and WhatsApp or Paystack checkout',
      'AI generates compelling product descriptions and SEO titles for every item automatically',
      'Mobile optimized, fast loading, and ready to receive orders from day one',
    ],
    price: 600,
    priceLabel: '$600',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r6',
    name: 'Instagram DM Auto-Responder Bot',
    category: 'ready',
    icon: MessageSquare,
    niche: 'Social Media & Sales',
    benefits: [
      'Automatically responds to Instagram DMs with personalized replies based on keywords',
      'Qualifies leads, answers FAQs and routes serious buyers to WhatsApp without manual effort',
      'Runs 24/7 so no lead goes cold while the business owner is unavailable or asleep',
    ],
    price: 400,
    priceLabel: '$400',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r7',
    name: 'Restaurant Menu & Ordering Website',
    category: 'ready',
    icon: Store,
    niche: 'Food & Hospitality',
    benefits: [
      'Clean digital menu website with photos, prices and category filters for any restaurant or food business',
      'Customers place orders directly via WhatsApp with pre-filled order details from the menu',
      'No app needed, works on any phone, and eliminates the cost of third party delivery platforms',
    ],
    price: 250,
    priceLabel: '$250',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r8',
    name: 'Crypto & Forex Signal Telegram Bot',
    category: 'ready',
    icon: TrendingUp,
    niche: 'Finance & Trading',
    benefits: [
      'Delivers AI-generated trading signals with entry, stop loss and take profit levels to your Telegram channel',
      'Monitors multiple pairs and assets simultaneously and alerts subscribers in real time',
      'Includes a performance tracker showing signal accuracy and win rate over time',
    ],
    price: 700,
    priceLabel: '$700',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r9',
    name: 'Business Landing Page with Lead Capture',
    category: 'ready',
    icon: Megaphone,
    niche: 'Marketing & Advertising',
    benefits: [
      'High converting single page website designed specifically to capture leads for ads and campaigns',
      'Includes headline, benefits section, testimonial placeholder, and WhatsApp or email CTA',
      'Delivered in 48 hours, fully mobile optimized and ready to connect to any ad campaign',
    ],
    price: 200,
    priceLabel: '$200',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'r10',
    name: 'Job Application Automation Bot',
    category: 'ready',
    icon: Briefcase,
    niche: 'Career & Recruitment',
    benefits: [
      'Scrapes job listings from LinkedIn, Indeed and local job boards matching your criteria daily',
      'Auto-fills and submits applications or sends personalized outreach to hiring managers automatically',
      'Tracks every application, response and follow-up in one organized dashboard',
    ],
    price: 350,
    priceLabel: '$350',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },

  // ══════════════════════════════
  // CUSTOM BUILDS — 10 products
  // ══════════════════════════════

  {
    id: 'c1',
    name: 'Coach AI Assistant',
    category: 'custom',
    icon: GraduationCap,
    niche: 'Online Coaching & Education',
    benefits: [
      'Trained on your exact frameworks, lessons and exercises so students get guidance in your voice 24/7',
      'Handles repetitive student questions automatically so you stop answering the same things over and over',
      'Integrated directly into your Circle, Skool or Kajabi community so students access it where they already are',
    ],
    price: 1500,
    priceLabel: 'From $1,500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c2',
    name: 'AI Agent for Law Firms',
    category: 'custom',
    icon: Scale,
    niche: 'Legal Services',
    benefits: [
      'Reviews contracts clause by clause, flags risks and delivers a structured report in minutes not hours',
      'Handles legal research queries with cited references so associates spend time on judgment not searching',
      'Drafts NDAs, service agreements and standard documents from prompts using your firm\'s own templates',
    ],
    price: 3000,
    priceLabel: 'From $3,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c3',
    name: 'Hospital Patient Intake AI System',
    category: 'custom',
    icon: Stethoscope,
    niche: 'Healthcare',
    benefits: [
      'Automates patient registration, symptom collection and appointment scheduling before the doctor is involved',
      'Reduces front desk workload by handling routine patient queries and follow-up reminders automatically',
      'Integrates with existing hospital management systems and delivers structured patient data to staff',
    ],
    price: 4000,
    priceLabel: 'From $4,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c4',
    name: 'Real Estate Lead Qualification Agent',
    category: 'custom',
    icon: Building2,
    niche: 'Real Estate',
    benefits: [
      'Automatically qualifies inbound leads by asking the right questions about budget, location and timeline',
      'Routes hot leads directly to agents via WhatsApp while nurturing cold leads with follow-up sequences',
      'Works across your website, Instagram DMs and WhatsApp simultaneously without extra staff',
    ],
    price: 2500,
    priceLabel: 'From $2,500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c5',
    name: 'E-commerce AI Customer Support Agent',
    category: 'custom',
    icon: ShoppingCart,
    niche: 'E-commerce',
    benefits: [
      'Handles order tracking, returns, refunds and FAQs automatically without human intervention',
      'Trained on your product catalog so it answers specific product questions accurately every time',
      'Escalates complex issues to human agents with full conversation context already attached',
    ],
    price: 2000,
    priceLabel: 'From $2,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c6',
    name: 'HR Recruitment Screening Agent',
    category: 'custom',
    icon: Users,
    niche: 'Human Resources',
    benefits: [
      'Screens job applications automatically against your criteria and shortlists qualified candidates instantly',
      'Conducts first-round screening interviews via chat and scores candidates before a human reviews them',
      'Reduces time-to-hire by up to 60% by eliminating manual CV reviews and initial screening calls',
    ],
    price: 2500,
    priceLabel: 'From $2,500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c7',
    name: 'Logistics & Delivery Tracking Bot',
    category: 'custom',
    icon: Truck,
    niche: 'Logistics & Supply Chain',
    benefits: [
      'Gives customers real-time delivery updates via WhatsApp or Telegram without calling dispatch',
      'Automates delivery confirmation, rescheduling requests and proof of delivery collection',
      'Reduces inbound customer service calls by up to 70% by answering delivery questions automatically',
    ],
    price: 2000,
    priceLabel: 'From $2,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c8',
    name: 'Hotel & Shortlet Management System',
    category: 'custom',
    icon: Hotel,
    niche: 'Hospitality',
    benefits: [
      'Manages bookings, availability calendars and guest communication from one central dashboard',
      'Automates check-in instructions, WiFi details and house rules delivery to guests on booking confirmation',
      'Syncs with Airbnb and Booking.com listings to prevent double bookings across platforms',
    ],
    price: 3500,
    priceLabel: 'From $3,500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c9',
    name: 'Financial Advisory Chatbot',
    category: 'custom',
    icon: DollarSign,
    niche: 'Finance & Fintech',
    benefits: [
      'Answers client questions about investment options, account balances and financial products 24/7',
      'Trained on your firm\'s specific products and compliance guidelines so answers are always accurate',
      'Qualifies prospects, books advisor consultations and sends follow-up reminders automatically',
    ],
    price: 3000,
    priceLabel: 'From $3,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'c10',
    name: 'School Parent Communication Agent',
    category: 'custom',
    icon: BookOpen,
    niche: 'Education',
    benefits: [
      'Handles parent enquiries about fees, timetables, events and report cards automatically via WhatsApp',
      'Sends automated reminders for fee payments, PTA meetings and school events to all parents at once',
      'Reduces administrative workload so school staff focus on education not answering repetitive messages',
    ],
    price: 2000,
    priceLabel: 'From $2,000',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },

  // ══════════════════════════════
  // IDEAS FOR SALE — 10 products
  // ══════════════════════════════

  {
    id: 'i1',
    name: 'Lexora — AI Legal Workspace',
    category: 'idea',
    icon: Scale,
    niche: 'Legal Technology',
    benefits: [
      'Complete AI workspace for law firms covering legal research, contract review, drafting and case filing',
      'Full execution plan including feature spec, tech stack, monetization model and go-to-market strategy',
      'A SaaS opportunity in a market where firms pay $500-2000 per month for legal tech tools',
    ],
    price: 650,
    priceLabel: '$650',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i2',
    name: 'ScoutBet — Sports Intelligence Platform',
    category: 'idea',
    icon: BarChart3,
    niche: 'Sports Betting & Analytics',
    benefits: [
      'Full platform concept for AI-powered match analysis, prediction engine and community for bettors',
      'Includes odds builder, accumulator tool, leaderboard and Telegram channel integration design',
      'Subscription model targeting the $81 billion sports betting market with a data-driven edge',
    ],
    price: 800,
    priceLabel: '$800',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i3',
    name: 'MediQueue — Hospital Waitlist & Triage App',
    category: 'idea',
    icon: Stethoscope,
    niche: 'Healthcare Technology',
    benefits: [
      'Patient-facing app that digitizes hospital queues, triage scoring and appointment management',
      'Reduces physical waiting room congestion by letting patients queue and track position from their phone',
      'Monetizes through hospital licensing fees — full business model and technical spec included',
    ],
    price: 500,
    priceLabel: '$500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i4',
    name: 'RentIQ — AI Property Management Assistant',
    category: 'idea',
    icon: Home,
    niche: 'Real Estate Technology',
    benefits: [
      'AI assistant for landlords and property managers handling tenant communication, rent reminders and maintenance requests',
      'Eliminates the need for a property manager for small to mid-size landlords managing 1-20 units',
      'Full product spec, pricing model and acquisition strategy targeting Nigeria and African property market',
    ],
    price: 500,
    priceLabel: '$500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i5',
    name: 'ShopAssist — WhatsApp Commerce AI',
    category: 'idea',
    icon: ShoppingCart,
    niche: 'E-commerce & Social Commerce',
    benefits: [
      'Turns any WhatsApp Business account into a fully functional store with AI-powered product recommendations',
      'Customers browse, ask questions, place orders and pay without leaving WhatsApp',
      'Targets the millions of Nigerian and African SME traders currently selling manually on WhatsApp',
    ],
    price: 600,
    priceLabel: '$600',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i6',
    name: 'TalentPipe — AI Recruitment Platform for African Startups',
    category: 'idea',
    icon: Users,
    niche: 'HR Technology',
    benefits: [
      'End-to-end recruitment platform built for African startups — job posting, screening, interviews and offers',
      'AI matches candidates to roles based on skills not just CV keywords reducing bad hires significantly',
      'Subscription SaaS model targeting the growing African startup ecosystem — full business plan included',
    ],
    price: 550,
    priceLabel: '$550',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i7',
    name: 'ClassBot — AI Tutor for Secondary School Students',
    category: 'idea',
    icon: GraduationCap,
    niche: 'EdTech',
    benefits: [
      'AI tutoring platform for WAEC and JAMB exam preparation with personalized study plans per student',
      'Parents pay a monthly subscription for their child to get 24/7 homework help and exam practice',
      'Massive untapped market across Nigeria and West Africa where exam prep is a high priority spend',
    ],
    price: 500,
    priceLabel: '$500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i8',
    name: 'FreightBot — Logistics Quoting & Booking Agent',
    category: 'idea',
    icon: Truck,
    niche: 'Logistics & Freight',
    benefits: [
      'AI agent that handles freight quoting, booking confirmation and shipment tracking for logistics companies',
      'Customers get instant quotes via WhatsApp or web without calling or waiting for a sales rep',
      'Full technical spec and go-to-market plan for a SaaS tool targeting African logistics operators',
    ],
    price: 500,
    priceLabel: '$500',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i9',
    name: 'ClinicDesk — Private Clinic Management System',
    category: 'idea',
    icon: ClipboardList,
    niche: 'Healthcare',
    benefits: [
      'All-in-one management system for private clinics covering appointments, patient records and billing',
      'Replaces expensive legacy medical software with a modern affordable tool built for small practices',
      'Recurring revenue SaaS model — full feature roadmap, pricing tiers and market sizing included',
    ],
    price: 600,
    priceLabel: '$600',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },
  {
    id: 'i10',
    name: 'BrandAI — AI Marketing Assistant for SMEs',
    category: 'idea',
    icon: Megaphone,
    niche: 'Marketing Technology',
    benefits: [
      'AI tool that generates social media content, ad copy, email campaigns and brand strategy for small businesses',
      'Small business owners get a full marketing department in one tool without hiring an agency',
      'Monthly subscription model with massive addressable market — full execution plan and tech stack included',
    ],
    price: 450,
    priceLabel: '$450',
    telegramDemoLink: 'https://t.me/forgebuilds',
  },

  // ══════════════════════════════
// READY TO BUY — 3 more
// ══════════════════════════════

{
  id: 'r11',
  name: 'WhatsApp Broadcast Marketing Tool',
  category: 'ready',
  icon: Megaphone,
  niche: 'Marketing & Sales',
  benefits: [
    'Send personalized broadcast messages to hundreds of WhatsApp contacts simultaneously without being flagged',
    'Schedule campaigns in advance with custom templates for promotions, follow-ups and announcements',
    'Built-in contact manager and delivery tracking so you know exactly who received and engaged with each message',
  ],
  price: 400,
  priceLabel: '$400',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'r12',
  name: 'AI Content Repurposing Bot',
  category: 'ready',
  icon: Cpu,
  niche: 'Content Creation & Marketing',
  benefits: [
    'Takes one long-form piece of content and automatically generates Twitter threads, LinkedIn posts, email newsletters and short captions',
    'Maintains your brand voice and tone across every platform so content feels consistent not robotic',
    'Saves content creators and marketers 4 to 6 hours per week on manual content reformatting',
  ],
  price: 350,
  priceLabel: '$350',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'r13',
  name: 'Competitor Price Monitoring Tool',
  category: 'ready',
  icon: Database,
  niche: 'E-commerce & Retail',
  benefits: [
    'Monitors competitor product prices across websites and marketplaces daily and alerts you when prices change',
    'Tracks up to 50 competitor products simultaneously and delivers a clean daily report to your email or Telegram',
    'Helps e-commerce businesses stay competitive by reacting to price changes before losing sales',
  ],
  price: 450,
  priceLabel: '$450',
  telegramDemoLink: 'https://t.me/forgebuilds',
},

// ══════════════════════════════
// CUSTOM BUILDS — 3 more
// ══════════════════════════════

{
  id: 'c11',
  name: 'Church & Ministry Management System',
  category: 'custom',
  icon: Users,
  niche: 'Religious Organisations',
  benefits: [
    'Manages member records, attendance tracking, tithe and offering records all in one organized system',
    'Sends automated WhatsApp or SMS reminders for services, events and follow-ups to members and visitors',
    'Gives church leadership a dashboard showing growth, giving trends and member engagement at a glance',
  ],
  price: 2000,
  priceLabel: 'From $2,000',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'c12',
  name: 'AI-Powered Social Media Manager',
  category: 'custom',
  icon: Megaphone,
  niche: 'Marketing Agencies & Brands',
  benefits: [
    'Generates, schedules and publishes content across Instagram, Twitter, LinkedIn and Facebook automatically',
    'Learns your brand voice over time and produces content that sounds human not AI-generated',
    'Includes a performance dashboard showing engagement, reach and best performing content per platform',
  ],
  price: 2500,
  priceLabel: 'From $2,500',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'c13',
  name: 'Inventory & Sales Management System',
  category: 'custom',
  icon: ClipboardList,
  niche: 'Retail & Distribution',
  benefits: [
    'Tracks stock levels in real time and sends automatic low-stock alerts before you run out of products',
    'Records every sale, generates daily and weekly revenue reports and tracks your best selling products',
    'Built for Nigerian SMEs and distributors managing physical products across one or multiple locations',
  ],
  price: 1800,
  priceLabel: 'From $1,800',
  telegramDemoLink: 'https://t.me/forgebuilds',
},

// ══════════════════════════════
// IDEAS FOR SALE — 4 more
// ══════════════════════════════

{
  id: 'i11',
  name: 'GigFlow — Freelancer Project & Payment Platform',
  category: 'idea',
  icon: Briefcase,
  niche: 'Freelance & Gig Economy',
  benefits: [
    'Platform where freelancers and clients agree on scope, milestones and payment in one place with escrow protection',
    'Solves the biggest problem in African freelancing — getting paid reliably and on time without disputes',
    'Full product spec, monetization model and go-to-market plan targeting Nigeria and pan-African gig workers',
  ],
  price: 600,
  priceLabel: '$600',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'i12',
  name: 'PulseDesk — AI Customer Support Platform for African SMEs',
  category: 'idea',
  icon: Phone,
  niche: 'Customer Service Technology',
  benefits: [
    'Unified inbox that pulls together WhatsApp, Instagram DMs, email and Facebook messages in one dashboard',
    'AI handles tier-one support automatically while escalating complex issues to human agents seamlessly',
    'Subscription SaaS targeting the millions of Nigerian businesses currently managing customer messages manually across five apps',
  ],
  price: 650,
  priceLabel: '$650',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'i13',
  name: 'SafeGuard — AI Fraud Detection System for Fintech',
  category: 'idea',
  icon: Shield,
  niche: 'Fintech & Banking',
  benefits: [
    'Real-time transaction monitoring system that flags suspicious activity and blocks fraudulent transactions before they complete',
    'Trained on African transaction patterns so it catches fraud that generic western models miss entirely',
    'Full technical architecture, compliance considerations and B2B SaaS pricing model targeting Nigerian fintechs and neobanks',
  ],
  price: 800,
  priceLabel: '$800',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
{
  id: 'i14',
  name: 'EventIQ — AI Event Planning & Ticketing Platform',
  category: 'idea',
  icon: Calendar,
  niche: 'Events & Entertainment',
  benefits: [
    'End-to-end event management platform covering planning, ticketing, attendee communication and post-event analytics',
    'AI suggests optimal pricing, predicts attendance and automates reminder sequences to maximize ticket sales',
    'Full execution plan targeting Nigeria\'s growing events industry — concerts, conferences, weddings and corporate events',
  ],
  price: 550,
  priceLabel: '$550',
  telegramDemoLink: 'https://t.me/forgebuilds',
},
]

export const productCategories = [
  { id: 'all', label: 'All' },
  { id: 'ready', label: 'Ready to Buy' },
  { id: 'custom', label: 'Custom Builds' },
  { id: 'idea', label: 'Ideas for Sale' },
]